### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by fvoordeckers** [ybugio/ybug-vue#1]
Currently there is no typescript support.
Without a type definition file the typing is just `any` and meaningless in TS.

**Comment by ybugio** [comment]
Hi @fvoordeckers , thanks for opening this issue. 
You are right, adding TS types will be useful!

**Comment by ybugio** [comment]
Hi @fvoordeckers, in the release 1.2.0 we rewrote everything to Typescript. I hope this helps :-)
